services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cse135
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html:ro
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf:ro
    restart: unless-stopped

  node:
    build:
      context: ./node-app
    container_name: cse135-node
    volumes:
      - ./node-app:/app
      - /app/node_modules
    restart: unless-stopped
  
  reporting:
    build:
      context: ./reporting.benyezhi.site/node-app/
      dockerfile: Dockerfile
    container_name: reporting-site
    ports:
      - "4001:3000"
    # environment:
    #   - NODE_ENV=production
    restart: always