
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cse135
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html:ro
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf:ro
    restart: unless-stopped

  node:
    build:
      context: ./reporting.benyezhi.site/node-app
    container_name: cse135-node
    ports:
      - "3000:3000"
    volumes:
      # - ./node-app:/app
      - /app/node_modules
    env_file:
      - ./reporting.benyezhi.site/node-app/.env
    restart: unless-stopped
  
  mysql-db:
    image: mysql:8.0
    container_name: mysql_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: analytics_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: your_actual_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./reporting.benyezhi.site/sql_scripts:/docker-entrypoint-initdb.d:ro
volumes:
  mysql_data:
