ServerName localhost
Listen 81
Listen 82

<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    ProxyPreserveHost On
    ProxyPass /node/ http://app:3000/node/
    ProxyPassReverse /node/ http://app:3000/node/
    ProxyPass /api http://app:3000/api
    ProxyPassReverse /api http://app:3000/api
    ProxyPass /reporting/ http://app:3000/
    ProxyPassReverse /reporting/ http://app:3000/

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ScriptAlias /cgi-bin/ /usr/bin/cgi-bin/
    <Directory "/usr/bin/cgi-bin">
        AllowOverride None
        Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:81>
    ServerAdmin webmaster@localhost

    ProxyPreserveHost On
    ProxyPass / http://app:3000/
    ProxyPassReverse / http://app:3000/

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

<VirtualHost *:82>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/collector

    ProxyPreserveHost On
    ProxyPass /log http://app:3000/log
    ProxyPassReverse /log http://app:3000/log
    ProxyPass /log-noscript http://app:3000/log-noscript
    ProxyPassReverse /log-noscript http://app:3000/log-noscript

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory /var/www/collector>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
